### ISSUE TITLE
[Suggestion] Pseudo-SwiftUI support.

### ISSUE THREAD

**Issue by ghost** [infinum/iOS-Loggie#28]
Hello,
I am integrating Loggie to a SwiftUI application. I see, that the `LoggieManager.shared.showLogs` method requires a UIViewController object to present the Loggie screen onto.
In my case with SwiftUI I had to provide a dummy UIViewController object to satisfy the method argument requirements, but this is not a practical approach.

Given the fact, that the aforementioned function returns a `UINavigationController`, even though it is `@discardableResult`, my suggestion is to make the UIViewController method argument optional with a default value of nil and perhaps using `viewController.flatMap { $0.present(navigationController, animated: true, completion: nil) }` to present Loggie in UIKit based apps, and using custom View - in SwiftUI apps.

I will clone and make an example later, and will open a PR, hopefully with an acceptable solution.

Best regards, L.

**Comment by hhrvoic** [comment]
@Lyubo4Infinum I guess we can add support for the SwiftUI as a part of a new View/modifier/whatever is needed for SwiftUI support? Did you had a chance to try it out?

**Comment by dimovskidamjan** [comment]
This was implemented in v2.3.5.
