### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by Truba** [infinum/iOS-Loggie#32]
Can we please get support for macOS.

**Comment by nikolamajcen** [comment]
The feature request has been created, and we'll try to add support for macOS in future releases.

**Comment by jcavar** [comment]
Hey guys, I looked into this briefly and there are two ways:

1. Rewrite all UIKit code in AppKit
2. Use SwiftUI

By using SwiftUI, we would be able to do it much more easily, but we would need to increase deployment target significantly.

**Comment by hhrvoic** [comment]
I also think SwiftUI is way to go. 
https://github.com/infinum/iOS-Loggie/pull/31, we already have SwiftUI support merged, could we use that for MacOS?

**Comment by jcavar** [comment]
Loggie is deprecated in favour of Pulse and Pulse already supports macOS:

https://github.com/infinum/ios-loggie/pull/43
